name: CI-CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
    - uses: actions/checkout@v4
    # Install nodejs dependencies and libraries
    - name: Install dependencies
      run: npx yarn
    # Build the code
    - name: Build
      run: npx yarn build
    # Archives the contents of the dist folder and uploads it to an artifactory system
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with: 
        name: assets
        path: dist
